services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
      target: prod
    ports:
      - "4321:4321"
